#   # expectedOutput:
#   #   dirs: [
#   #     Testing/DifferentDirectoryStructureDifferentFilesFlat/DiffTargetB/C
#   #   ]
#   #   files: [
#   #     Testing/DifferentDirectoryStructureDifferentFilesFlat/DiffTargetB/fileC.txt
#   #   ]
# DifferentDirectoryStructureDifferentFilesFlat:
#   setup:
#     DiffTargetA:
#       A
#       B
#       C
#       fileA.txt
#       fileB.txt
#       fileC.txt
#     DiffTargetB:
#       A
#       B
#       fileA.txt
#       fileB.txt
#   expectedOutput:
#     dirs: [
#       DiffTargetB/C
#     ]
#     files: [
#       DiffTargetB/fileC.txt
#     ]


# DifferentDirectoryStructureDifferentFilesNested:
#   setup:
#     DiffTargetA:
#       A:
#         F: []
#         E:
#           fileA.txt
#           fileB.txt
#           fileC.txt
#     DiffTargetB:
#       A:
#         E:
#           fileA.txt
#           fileB.txt

#   expectedOutput:
#     dirs: [] 
#     files: []

#     dirs: [
#       DiffTargetB/A/F
#     ] 
#     files: [
#       DiffTargetB/A/E/fileC.txt
#     ]
  



# DifferentDirectoryStructureDifferentFilesNested:
#   setup:
#     DiffTargetA:
#       A:
#         F: []
#         E: [
#           fileA.txt,
#           fileB.txt,
#           fileC.txt,
#         ]
#     DiffTargetB:
#       A:
#         E: [
#           fileA.txt
#           fileB.txt
#         ]

#   expectedOutput:
#     dirs: [] 
#     files: []

#     dirs: [
#       DiffTargetB/A/F
#     ] 
#     files: [
#       DiffTargetB/A/E/fileC.txt
#     ]





# D:
#   files: [ "a", "b", "c"]
#   dirs: 
#     J:
#       files: ["c", "d"]
#     K:

DifferentDirectoryStructureDifferentFilesFlat:
  setup:
    DiffTargetA:
      files: [
        fileA.txt,
        fileB.txt,
        fileC.txt,
      ]
      dirs:
        A:
        B:
        C: 
    DiffTargetB:
      files: [
        fileA.txt,
        fileB.txt,
      ]
      dirs:
        A:
        B:
  expectedOutput:
    files: [
      DiffTargetB/fileC.txt
    ]
    dirs: [
      DiffTargetB/C
    ]

DifferentDirectoryStructureDifferentFilesNested:
  setup:
    DiffTargetA:
      dirs:
        F:
        A:
          files: [
            fileA.txt,
            fileB.txt,
            fileC.txt,
          ]
          dirs:
            E:
    
    DiffTargetB:
      dirs:
        A:
          files: [
            fileA.txt,
            fileB.txt,
          ]
          dirs:
            E:
          
  expectedOutput:
    dirs: [
      DiffTargetB/A/F
    ] 
    files: [
      DiffTargetB/A/E/fileC.txt
    ]

DifferentDirectoryStructureFlat:
  setup:
    DiffTargetA:
      dirs:
        A:
        B:
        C:
    DiffTargetB:
      dirs:
        A:
        B:
  expectedOutput:
    dirs: [
      DiffTargetB/C
    ]
    files: []

# DeeplyNestedFileDifference:
#   setup:
#     DiffTargetA:
#       dirs:
#         A:
#           dirs:
#             B:
#               dirs:
#                 C:
#                   dirs:
#                     D:
#                   files: [
#                     1.txt,
#                     2.txt
#                   ]
#     DiffTargetB:
#       dirs:
#         A:
#           dirs:
#             B:
#               dirs:
#                 C:
#                   dirs:
#                     D:
#                   files: [
#                     1.txt
#                   ]

# DeeplyNestedDirectoryDifference:
#   setup:
#     DiffTargetA:
#       dirs:
#         A:
#           dirs:
#             B:
#               dirs:
#                 C:
#                   dirs:
#                     D:
#                     E:
#                   files: [
#                     1.txt,
#                     2.txt
#                   ]
#     DiffTargetB:
#       dirs:
#         A:
#           dirs:
#             B:
#               dirs:
#                 C:
#                   dirs:
#                     D:
#                   files: [
#                     1.txt,
#                     2.txt
#                   ]


# DifferentDirectoryStructureNested:
#   setup:
#     DiffTargetA:
#       - A:
#         - E: []
#         - F: []
#       - B: []
#       - C: []
    
#     DiffTargetB:
#       - A:
#         - E: []
#       - B: []
#       - C: []

# DifferentFilesFlat:
#   setup:
#     DiffTargetA:
#       - fileA.txt
#       - fileB.txt
#       - fileC.txt
#     DiffTargetB:
#       - fileA.txt
#       - fileB.txt

# DifferentFilesNested:
#   setup:
#     DiffTargetA:
#       - A:
#         - E:
#           - fileA.txt
#           - fileB.txt
#           - fileC.txt
#     DiffTargetB:
#       - A:
#         - E:
#           - fileA.txt
#           - fileB.txt

# SameDirectoryStructureFlat:
#   setup:
#     DiffTargetA:
#       - A: []
#       - B: []
#       - C: []
    
#     DiffTargetB:
#       - A: []
#       - B: []
#       - C: []

# SameDirectoryStructureNested:
#   setup:
#     DiffTargetA:
#       - A:
#         - E: []
#         - F: []
#       - B: []
#       - C: []
    
#     DiffTargetB:
#       - A:
#         - E: []
#         - F: []
#       - B: []
#       - C: []

# SameFilesFlat:
#   setup:
#     DiffTargetA:
#       - fileA.txt
#       - fileB.txt
#       - fileC.txt
#     DiffTargetB:
#       - fileA.txt
#       - fileB.txt
#       - fileC.txt

# SameFilesNested:
#   setup:
#     DiffTargetA:
#       - A:
#         - E:
#           - fileA.txt
#           - fileB.txt
#           - fileC.txt
    
#     DiffTargetB:
#       - A:
#         - E:
#           - fileA.txt
#           - fileB.txt
#           - fileC.txt