version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build:
    executor: python/default
    working_directory: ~/DiffDrives
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Remove existing Testing dir if exists
          command: rm -rf Testing
      - run:
          name: Generate testing data
          command: python3 TestConfigParser.py
      - run:
          name: Make test result directory
          command:  mkdir test-results
      - run:
          name: Run tests
          command:  pytest --junitxml=test-results/junit.xml -sv
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

