version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Make test result directory
          command:  mkdir test-results
      - run:
          name: Run tests
          command:  pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

#workflows:
#  main:
#    jobs:
#      - python/test:
#          test-tool: pytest
